In [14]:
import pandas as pd

test_df = pd.read_csv('../data/original_data/ais_test.csv')
schedules_df = pd.read_csv('../data/original_data/schedules_to_may_2024.csv', sep='|')

test_df.head()

   ID                  vesselId                 time  scaling_factor
0   0  61e9f3aeb937134a3c4bfe3d  2024-05-08 00:03:16             0.3
1   1  61e9f473b937134a3c4c02df  2024-05-08 00:06:17             0.3
2   2  61e9f469b937134a3c4c029b  2024-05-08 00:10:02             0.3
3   3  61e9f45bb937134a3c4c0221  2024-05-08 00:10:34             0.3
4   4  61e9f38eb937134a3c4bfd8d  2024-05-08 00:12:27             0.3

In [15]:
schedules_df.head()

,vesselId,shippingLineId,shippingLineName,arrivalDate,sailingDate,portName,portId,portLatitude,portLongitude
0,61e9f3b1b937134a3c4bfe53,61a8e672f9cba188601e84ac,Wallenius Wilhelmsen Ocean,2023-10-02 00:00:00+00:00,2023-10-03 00:00:00+00:00,Port of Brunswick,61d38499b7b7526e1adf3d54,31.140556,-81.496667
1,61e9f3b1b937134a3c4bfe53,61a8e672f9cba188601e84ac,Wallenius Wilhelmsen Ocean,2023-10-27 00:00:00+00:00,2023-10-27 00:00:00+00:00,Port of Southampton,61d3832bb7b7526e1adf3b63,50.902500,-1.428889
2,61e9f3b1b937134a3c4bfe53,61a8e672f9cba188601e84ac,Wallenius Wilhelmsen Ocean,2023-10-19 00:00:00+00:00,2023-10-20 00:00:00+00:00,Port of Bremerhaven,61d375e793c6feb83e5eb3e2,53.563611,8.554722
3,61e9f3b1b937134a3c4bfe53,61a8e672f9cba188601e84ac,Wallenius Wilhelmsen Ocean,2023-10-09 00:00:00+00:00,2023-10-10 00:00:00+00:00,Port of New York,61d38481b7b7526e1adf3d23,40.688333,-74.028611
4,61e9f3b1b937134a3c4bfe53,61a8e672f9cba188601e84ac,Wallenius Wilhelmsen Ocean,2023-09-25 00:00:00+00:00,2023-09-26 00:00:00+00:00,Manzanillo International Terminal,61d37d0199db2ccf7339eee1,9.372370,-79.879790

In [16]:
import pandas as pd
import numpy as np
from datetime import datetime

def engineer_port_locations(schedule_df, test_df):
    """
    Engineer port latitude and longitude features for test data based on vessel schedules.
    Handles timezone-aware datetime comparisons.
    
    Parameters:
    schedule_df (pd.DataFrame): Schedule data with vessel ports and times
    test_df (pd.DataFrame): Test data requiring port location features
    
    Returns:
    pd.DataFrame: Test data with added port_lat and port_long features
    """
    # Convert string data to datetime and ensure timezone consistency
    schedule_df = schedule_df.copy()
    test_df = test_df.copy()
    
    # Convert schedule dates to UTC
    schedule_df['arrivalDate'] = pd.to_datetime(schedule_df['arrivalDate']).dt.tz_convert('UTC')
    schedule_df['sailingDate'] = pd.to_datetime(schedule_df['sailingDate']).dt.tz_convert('UTC')
    
    # Convert test dates to UTC
    test_df['time_utc'] = pd.to_datetime(test_df['time']).dt.tz_localize('UTC')
    
    # Initialize new columns
    test_df['port_lat'] = np.nan
    test_df['port_long'] = np.nan
    
    # Process each row in test_df
    for idx, row in test_df.iterrows():
        vessel_schedule = schedule_df[schedule_df['vesselId'] == row['vesselId']].copy()
        
        if len(vessel_schedule) == 0:
            continue
            
        # Sort vessel schedule by arrival date
        vessel_schedule = vessel_schedule.sort_values('arrivalDate')
        
        # Find the relevant port
        # Case 1: Vessel is at a port (between arrival and sailing)
        at_port = vessel_schedule[
            (vessel_schedule['arrivalDate'] <= row['time_utc']) & 
            (vessel_schedule['sailingDate'] >= row['time_utc'])
        ]
        
        if len(at_port) > 0:
            # Use the current port's coordinates
            test_df.at[idx, 'port_lat'] = at_port.iloc[0]['portLatitude']
            test_df.at[idx, 'port_long'] = at_port.iloc[0]['portLongitude']
            continue
        
        # Case 2: Vessel is between ports
        next_port = vessel_schedule[vessel_schedule['arrivalDate'] > row['time_utc']].iloc[0] if len(vessel_schedule[vessel_schedule['arrivalDate'] > row['time_utc']]) > 0 else None
        prev_port = vessel_schedule[vessel_schedule['sailingDate'] < row['time_utc']].iloc[-1] if len(vessel_schedule[vessel_schedule['sailingDate'] < row['time_utc']]) > 0 else None
        
        if prev_port is not None and next_port is not None:
            # Calculate time ratios
            total_time = (next_port['arrivalDate'] - prev_port['sailingDate']).total_seconds()
            elapsed_time = (row['time_utc'] - prev_port['sailingDate']).total_seconds()
            ratio = elapsed_time / total_time
            
            # Interpolate coordinates
            test_df.at[idx, 'port_lat'] = prev_port['portLatitude'] + (next_port['portLatitude'] - prev_port['portLatitude']) * ratio
            test_df.at[idx, 'port_long'] = prev_port['portLongitude'] + (next_port['portLongitude'] - prev_port['portLongitude']) * ratio
        
        elif prev_port is not None:
            # Use last known port
            test_df.at[idx, 'port_lat'] = prev_port['portLatitude']
            test_df.at[idx, 'port_long'] = prev_port['portLongitude']
        
        elif next_port is not None:
            # Use next port
            test_df.at[idx, 'port_lat'] = next_port['portLatitude']
            test_df.at[idx, 'port_long'] = next_port['portLongitude']

    test_df.drop(["time_utc"], axis=1, inplace=True)
    
    return test_df

test_df = engineer_port_locations(test_df=test_df, schedule_df=schedules_df)

In [17]:
test_df.head(50)

,ID,vesselId,time,scaling_factor,port_lat,port_long
0,0,61e9f3aeb937134a3c4bfe3d,2024-05-08 00:03:16,0.3,53.534403,8.367380
1,1,61e9f473b937134a3c4c02df,2024-05-08 00:06:17,0.3,NaN,NaN
2,2,61e9f469b937134a3c4c029b,2024-05-08 00:10:02,0.3,NaN,NaN
3,3,61e9f45bb937134a3c4c0221,2024-05-08 00:10:34,0.3,NaN,NaN
4,4,61e9f38eb937134a3c4bfd8d,2024-05-08 00:12:27,0.3,NaN,NaN
5,5,clh6aqawa0006gh0zje911dl3,2024-05-08 00:12:31,0.3,NaN,NaN
6,6,61e9f3c7b937134a3c4bfedf,2024-05-08 00:13:58,0.3,NaN,NaN
7,7,61e9f3b0b937134a3c4bfe4f,2024-05-08 00:14:41,0.3,51.336389,3.207222
8,8,61e9f446b937134a3c4c01ab,2024-05-08 00:15:03,0.3,NaN,NaN
9,9,61e9f3cbb937134a3c4bff03,2024-05-08 00:15:34,0.3,NaN,NaN
10,10,61e9f3aeb937134a3c4bfe43,2024-05-08 00:15:44,0.3,51.336389,3.207222
11,11,61e9f469b937134a3c4c0295,2024-05-08 00:16:00,0.3,NaN,NaN
12,12,630fede7698dd2548ac1ee66,2024-05-08 00:16:24,0.3,NaN,NaN
13,13,61e9f3c8b937134a3c4bfee3,2024-05-08 00:16:29,0.3,NaN,NaN
14,14,61e9f3f2b937134a3c4bffa1,2024-05-08 00:16:31,0.3,39.716667,-75.521667
15,15,631fc1ccfe2331c1cf4131de,2024-05-08 00:16:32,0.3,59.736667,10.229722
16,16,6326f5a6c46d6a20d22ca31e,2024-05-08 00:16:33,0.3,NaN,NaN
17,17,631e3d5e192150e13fa41626,2024-05-08 00:16:33,0.3,NaN,NaN
18,18,61e9f3c8b937134a3c4bfee5,2024-05-08 00:16:34,0.3,NaN,NaN
19,19,61e9f466b937134a3c4c0273,2024-05-08 00:16:47,0.3,NaN,NaN
20,20,6323f2287abc89c0a9631e57,2024-05-08 00:16:48,0.3,NaN,NaN
21,21,61e9f422b937134a3c4c00c3,2024-05-08 00:16:49,0.3,NaN,NaN
22,22,61e9f403b937134a3c4c0011,2024-05-08 00:16:50,0.3,NaN,NaN
23,23,61e9f411b937134a3c4c004d,2024-05-08 00:16:52,0.3,50.902500,-1.428889
24,24,61e9f3fbb937134a3c4bffd5,2024-05-08 00:16:57,0.3,NaN,NaN
25,25,61e9f452b937134a3c4c01e9,2024-05-08 00:17:00,0.3,NaN,NaN
26,26,61e9f468b937134a3c4c028f,2024-05-08 00:17:02,0.3,NaN,NaN
27,27,61e9f463b937134a3c4c0255,2024-05-08 00:17:02,0.3,NaN,NaN
28,28,61e9f465b937134a3c4c026d,2024-05-08 00:17:03,0.3,NaN,NaN
29,29,61e9f466b937134a3c4c0275,2024-05-08 00:17:15,0.3,NaN,NaN
30,30,61e9f3acb937134a3c4bfe2d,2024-05-08 00:17:19,0.3,34.688506,135.260161
31,31,61e9f429b937134a3c4c00e3,2024-05-08 00:17:21,0.3,NaN,NaN
32,32,61e9f3c8b937134a3c4bfeed,2024-05-08 00:17:22,0.3,NaN,NaN
33,33,61e9f3cbb937134a3c4bff07,2024-05-08 00:17:23,0.3,NaN,NaN
34,34,61e9f465b937134a3c4c026b,2024-05-08 00:17:26,0.3,NaN,NaN
35,35,61e9f3adb937134a3c4bfe39,2024-05-08 00:17:27,0.3,29.304167,-94.818611
36,36,61e9f3f3b937134a3c4bffab,2024-05-08 00:17:29,0.3,51.336389,3.207222
37,37,61e9f39ab937134a3c4bfdbb,2024-05-08 00:17:31,0.3,-34.462500,150.899444
38,38,61e9f3fdb937134a3c4bffe1,2024-05-08 00:17:32,0.3,53.538683,8.406674
39,39,61e9f42ab937134a3c4c00eb,2024-05-08 00:17:33,0.3,NaN,NaN
40,40,61e9f452b937134a3c4c01ed,2024-05-08 00:17:35,0.3,NaN,NaN
41,41,61e9f413b937134a3c4c0059,2024-05-08 00:17:37,0.3,NaN,NaN
42,42,621f63e858ea7fcc9448e43c,2024-05-08 00:17:41,0.3,NaN,NaN
43,43,61e9f46bb937134a3c4c02ad,2024-05-08 00:17:43,0.3,NaN,NaN
44,44,61e9f3c1b937134a3c4bfea7,2024-05-08 00:17:46,0.3,1.292778,103.725278
45,45,62f94e6102767739ab32c7aa,2024-05-08 00:17:53,0.3,NaN,NaN
46,46,61e9f431b937134a3c4c0115,2024-05-08 00:17:54,0.3,-27.382500,153.169444
47,47,61e9f443b937134a3c4c0197,2024-05-08 00:17:56,0.3,53.563611,8.554722
48,48,61e9f41eb937134a3c4c009d,2024-05-08 00:18:02,0.3,53.524722,9.963333
49,49,61e9f3b8b937134a3c4bfe87,2024-05-08 00:18:04,0.3,15.700000,-88.617000

In [18]:
test_df.to_csv("../data/processed_data/test.csv", index=False)